-- 중복 된 컬럼을 제거하는 DISTINCT
SELECT
	   CATEGORY_CODE
  FROM TBL_MENU
 ORDER BY CATEGORY_CODE;
 
SELECT
	   distinct CATEGORY_CODE
  FROM TBL_MENU
 ORDER BY CATEGORY_CODE;
 
 SELECT DISTINCT
		CATEGORY_CODE,
        ORDERABLE_STATUS
   FROM TBL_MENU;     