-- GROUP BY : 여러개의 결과가 있는 컬럼을 묶는 역할
SELECT
	   CATEGORY_CODE
  FROM TBL_MENU
 GROUP BY CATEGORY_CODE; 
 
SELECT
	   CATEGORY_CODE,
       COUNT(*)
  FROM TBL_MENU
 GROUP BY CATEGORY_CODE;
 
SELECT
	   CATEGORY_CODE,
       SUM(MENU_PRICE)
  FROM TBL_MENU
 GROUP BY CATEGORY_CODE;
 
SELECT
	   CATEGORY_CODE,
       AVG(MENU_PRICE)
  FROM TBL_MENU
 GROUP BY CATEGORY_CODE; 
 
-- HAVING
SELECT
	   CATEGORY_CODE
  FROM TBL_MENU
 GROUP BY CATEGORY_CODE
HAVING CATEGORY_CODE IN (5, 6, 7, 8);

-- 카테고리별 총 합 구하는 ROLLUP
SELECT
	   CATEGORY_CODE,
       SUM(MENU_PRICE)
  FROM TBL_MENU
 GROUP BY CATEGORY_CODE
  WITH ROLLUP;
  
SELECT
	   MENU_PRICE,
       CATEGORY_CODE,
       SUM(MENU_PRICE)
  FROM TBL_MENU
 GROUP BY MENU_PRICE,
		  CATEGORY_CODE
  WITH ROLLUP;  
  
SELECT
	   CATEGORY_CODE
  FROM TBL_MENU
 WHERE MENU_NAME = '민트미역국';
 
SELECT
	   MENU_CODE,
       MENU_NAME,
       MENU_PRICE,
       CATEGORY_CODE,
       ORDERABLE_STATUS
  FROM TBL_MENU;
  
-- SUBQUERY
SELECT
	   MENU_CODE,
       MENU_NAME,
       MENU_PRICE,
       CATEGORY_CODE,
       ORDERABLE_STATUS
  FROM TBL_MENU
 WHERE CATEGORY_CODE = (SELECT
							   CATEGORY_CODE
						  FROM TBL_MENU
                         WHERE MENU_NAME = '민트미역국'); 

INSERT INTO TBL_MENU VALUES (NULL, '바나나해장국', 8500, 4, 'Y');  

SELECT
	   *
  FROM TBL_MENU;
  
DELETE FROM TBL_MENU
WHERE MENU_NAME = '바나나해장국';  